export const CATEGORY_THEMES = {
  all: {
    bg: "#FAFAF8",
    bgGradient: "linear-gradient(150deg, #FAFAF8 0%, #F0F7F2 50%, #FAFAF8 100%)",
    accent: "#1A6B3C",
    accentRgb: "26,107,60",
    text: "#0F1A0F",
    subText: "#4A6A52",
    cardBg: "#FFFFFF",
    borderColor: "#D8EBE0",
    fontFamily: "'Playfair Display', serif",
    tagline: "Every Category. One Destination.",
    headline: "Discover Our\nFull Collection",
    sub: "From beauty to tech, groceries to furniture — curated products at your fingertips.",
    stat1: { value: "100+", label: "Products" },
    stat2: { value: "20+", label: "Categories" },
    stat3: { value: "4.5★", label: "Avg Rating" },
    pill: "All Products",
    layout: "centered",
  },

  beauty: {
    bg: "#F8FAF8",
    bgGradient: "linear-gradient(160deg, #F8FAF8 0%, #EEF6F0 50%, #F8FAF8 100%)",
    accent: "#2D8653",
    accentRgb: "45,134,83",
    text: "#0A1F12",
    subText: "#4A7A58",
    cardBg: "#FFFFFF",
    borderColor: "#CBE8D6",
    fontFamily: "'Cormorant Garamond', serif",
    tagline: "Nurture Your Glow",
    headline: "Reveal Your\nNatural Beauty",
    sub: "Gentle formulas crafted to hydrate, restore, and elevate your skin every day.",
    stat1: { value: "60k", label: "Happy Clients" },
    stat2: { value: "100%", label: "Cruelty Free" },
    stat3: { value: "4.8★", label: "Rated" },
    pill: "Shop Beauty",
    layout: "editorial",
  },

  fragrances: {
    bg: "#F6FAF7",
    bgGradient: "linear-gradient(150deg, #F6FAF7 0%, #E8F4EC 50%, #F6FAF7 100%)",
    accent: "#1A7A4A",
    accentRgb: "26,122,74",
    text: "#081A10",
    subText: "#3D6E50",
    cardBg: "#FFFFFF",
    borderColor: "#C2E3CF",
    fontFamily: "'Cormorant Garamond', serif",
    tagline: "Scent is Memory",
    headline: "Find Your\nSignature Scent",
    sub: "Rare ingredients, masterful compositions. Fragrances that become unmistakably you.",
    stat1: { value: "200+", label: "Scents" },
    stat2: { value: "12", label: "Families" },
    stat3: { value: "Luxury", label: "Grade" },
    pill: "Explore Scents",
    layout: "editorial",
  },

  furniture: {
    bg: "#F7FAF8",
    bgGradient: "linear-gradient(150deg, #F7FAF8 0%, #EAF3ED 60%, #F7FAF8 100%)",
    accent: "#2E7D52",
    accentRgb: "46,125,82",
    text: "#0A1A10",
    subText: "#466B52",
    cardBg: "#FFFFFF",
    borderColor: "#C8E6D4",
    fontFamily: "'DM Serif Display', serif",
    tagline: "Craft for Living",
    headline: "Spaces That\nTell Your Story",
    sub: "Timeless pieces, honest materials. Furniture built to last generations.",
    stat1: { value: "50yr", label: "Durability" },
    stat2: { value: "FSC", label: "Certified" },
    stat3: { value: "Bespoke", label: "Made" },
    pill: "Browse Furniture",
    layout: "editorial",
  },

  groceries: {
    bg: "#F5FAF6",
    bgGradient: "linear-gradient(145deg, #F5FAF6 0%, #E6F4EA 50%, #F5FAF6 100%)",
    accent: "#1E8C45",
    accentRgb: "30,140,69",
    text: "#071510",
    subText: "#3A6A46",
    cardBg: "#FFFFFF",
    borderColor: "#BDE4CA",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    tagline: "Fresh. Local. Yours.",
    headline: "Farm to Door\nEvery Morning",
    sub: "Seasonal produce, pantry staples, and specialty foods — delivered fresh.",
    stat1: { value: "Daily", label: "Harvest" },
    stat2: { value: "Zero", label: "Pesticides" },
    stat3: { value: "2hr", label: "Delivery" },
    pill: "Shop Fresh",
    layout: "bold",
  },

  "home-decoration": {
    bg: "#F8FAF8",
    bgGradient: "linear-gradient(150deg, #F8FAF8 0%, #EDF5F0 50%, #F8FAF8 100%)",
    accent: "#3A7D5E",
    accentRgb: "58,125,94",
    text: "#0A1A12",
    subText: "#4A7060",
    cardBg: "#FFFFFF",
    borderColor: "#C5E2D4",
    fontFamily: "'Libre Baskerville', serif",
    tagline: "Style Your Space",
    headline: "Every Corner\nDeserves Beauty",
    sub: "Curated décor to transform any room into a space that feels like you.",
    stat1: { value: "500+", label: "Styles" },
    stat2: { value: "Gift", label: "Ready" },
    stat3: { value: "Award", label: "Winning" },
    pill: "Decorate Now",
    layout: "editorial",
  },

  "kitchen-accessories": {
    bg: "#F6FAF7",
    bgGradient: "linear-gradient(140deg, #F6FAF7 0%, #E8F4EC 50%, #F6FAF7 100%)",
    accent: "#256845",
    accentRgb: "37,104,69",
    text: "#081510",
    subText: "#3D6248",
    cardBg: "#FFFFFF",
    borderColor: "#C0DFD0",
    fontFamily: "'Playfair Display', serif",
    tagline: "Cook with Confidence",
    headline: "Tools Built for\nReal Kitchens",
    sub: "Professional-grade accessories for home chefs who take their craft seriously.",
    stat1: { value: "Chef", label: "Approved" },
    stat2: { value: "Steel", label: "Grade" },
    stat3: { value: "10yr", label: "Warranty" },
    pill: "Equip Kitchen",
    layout: "editorial",
  },

  laptops: {
    bg: "#F5FAF7",
    bgGradient: "linear-gradient(135deg, #F5FAF7 0%, #E4F2EA 50%, #F5FAF7 100%)",
    accent: "#1B6E42",
    accentRgb: "27,110,66",
    text: "#081510",
    subText: "#386048",
    cardBg: "#FFFFFF",
    borderColor: "#BAE0CC",
    fontFamily: "'Inter', sans-serif",
    tagline: "Power Your Work",
    headline: "Next-Gen Laptops\nFor Every Need",
    sub: "From ultra-thin to workstation-grade — performance laptops that keep up with you.",
    stat1: { value: "M4", label: "Chipsets" },
    stat2: { value: "4K", label: "Displays" },
    stat3: { value: "20hr", label: "Battery" },
    pill: "Shop Laptops",
    layout: "tech",
  },

  "mens-shirts": {
    bg: "#F7FAF8",
    bgGradient: "linear-gradient(150deg, #F7FAF8 0%, #EBF4EE 50%, #F7FAF8 100%)",
    accent: "#2A7550",
    accentRgb: "42,117,80",
    text: "#0A1A10",
    subText: "#426854",
    cardBg: "#FFFFFF",
    borderColor: "#C3E2D2",
    fontFamily: "'DM Serif Display', serif",
    tagline: "Dressed with Intent",
    headline: "The Modern\nGentleman's Edit",
    sub: "Premium fabrics, precise cuts. Shirts crafted for those who dress with purpose.",
    stat1: { value: "Slim", label: "Fit" },
    stat2: { value: "100%", label: "Cotton" },
    stat3: { value: "Tailored", label: "Cut" },
    pill: "Shop Shirts",
    layout: "editorial",
  },

  "mens-shoes": {
    bg: "#F6F9F7",
    bgGradient: "linear-gradient(135deg, #F6F9F7 0%, #E8F2EC 50%, #F6F9F7 100%)",
    accent: "#1F6B42",
    accentRgb: "31,107,66",
    text: "#081510",
    subText: "#3C6448",
    cardBg: "#FFFFFF",
    borderColor: "#C0DFCE",
    fontFamily: "'Cormorant Garamond', serif",
    tagline: "Walk with Authority",
    headline: "Shoes That Define\nYour Stride",
    sub: "Handcrafted leather, heritage silhouettes. Built for the man who means business.",
    stat1: { value: "Hand", label: "Crafted" },
    stat2: { value: "Full", label: "Grain Leather" },
    stat3: { value: "Classic", label: "Since 1998" },
    pill: "Shop Shoes",
    layout: "editorial",
  },

  "mens-watches": {
    bg: "#F5FAF6",
    bgGradient: "linear-gradient(135deg, #F5FAF6 0%, #E4F2E8 50%, #F5FAF6 100%)",
    accent: "#145C38",
    accentRgb: "20,92,56",
    text: "#071510",
    subText: "#325E42",
    cardBg: "#FFFFFF",
    borderColor: "#B8DEC8",
    fontFamily: "'Cormorant Garamond', serif",
    tagline: "Time is Everything",
    headline: "Precision\nPersonified",
    sub: "Swiss movements, sapphire crystals, timeless cases. A watch for every wrist.",
    stat1: { value: "Swiss", label: "Movement" },
    stat2: { value: "50m", label: "Water Resist" },
    stat3: { value: "Life", label: "Warranty" },
    pill: "Shop Watches",
    layout: "editorial",
  },

  "mobile-accessories": {
    bg: "#F5FAF7",
    bgGradient: "linear-gradient(135deg, #F5FAF7 0%, #E4F2EA 50%, #F5FAF7 100%)",
    accent: "#23845C",
    accentRgb: "35,132,92",
    text: "#081510",
    subText: "#3C6E54",
    cardBg: "#FFFFFF",
    borderColor: "#BAE0CE",
    fontFamily: "'Inter', sans-serif",
    tagline: "Stay Connected",
    headline: "Accessories for\nEvery Device",
    sub: "Cases, cables, chargers and more. Everything your phone needs, nothing it doesn't.",
    stat1: { value: "MFi", label: "Certified" },
    stat2: { value: "Fast", label: "Charge" },
    stat3: { value: "Drop", label: "Tested" },
    pill: "Shop Accessories",
    layout: "tech",
  },

  motorcycle: {
    bg: "#F6FAF7",
    bgGradient: "linear-gradient(140deg, #F6FAF7 0%, #E6F3EC 50%, #F6FAF7 100%)",
    accent: "#2B7048",
    accentRgb: "43,112,72",
    text: "#081510",
    subText: "#3E6448",
    cardBg: "#FFFFFF",
    borderColor: "#C0E0CE",
    fontFamily: "'DM Serif Display', serif",
    tagline: "Born to Ride",
    headline: "Gear Up for\nEvery Road",
    sub: "Helmets, gloves, jackets. Riding gear engineered for performance and protection.",
    stat1: { value: "DOT", label: "Certified" },
    stat2: { value: "CE", label: "Armour" },
    stat3: { value: "Race", label: "Grade" },
    pill: "Shop Moto",
    layout: "bold",
  },

  "skin-care": {
    bg: "#F8FAF8",
    bgGradient: "linear-gradient(160deg, #F8FAF8 0%, #ECF5EF 50%, #F8FAF8 100%)",
    accent: "#328058",
    accentRgb: "50,128,88",
    text: "#0A1A10",
    subText: "#4A7258",
    cardBg: "#FFFFFF",
    borderColor: "#C4E3D4",
    fontFamily: "'Cormorant Garamond', serif",
    tagline: "Skin Speaks First",
    headline: "Science-Backed\nSkin Rituals",
    sub: "Dermatologist-tested formulas that work with your skin, not against it.",
    stat1: { value: "Derm", label: "Tested" },
    stat2: { value: "Vegan", label: "Formula" },
    stat3: { value: "4.9★", label: "Rated" },
    pill: "Shop Skincare",
    layout: "editorial",
  },

  smartphones: {
    bg: "#F5FAF6",
    bgGradient: "linear-gradient(135deg, #F5FAF6 0%, #E3F2E8 50%, #F5FAF6 100%)",
    accent: "#196640",
    accentRgb: "25,102,64",
    text: "#071510",
    subText: "#365E44",
    cardBg: "#FFFFFF",
    borderColor: "#B8DEC8",
    fontFamily: "'Inter', sans-serif",
    tagline: "Pocket-Sized Power",
    headline: "The Smartphone\nYou Deserve",
    sub: "Latest flagships, mid-range gems, and budget picks. Find your perfect match.",
    stat1: { value: "5G", label: "Ready" },
    stat2: { value: "108MP", label: "Cameras" },
    stat3: { value: "All", label: "Brands" },
    pill: "Shop Phones",
    layout: "tech",
  },

  "sports-accessories": {
    bg: "#F4FAF6",
    bgGradient: "linear-gradient(140deg, #F4FAF6 0%, #E2F3E9 50%, #F4FAF6 100%)",
    accent: "#1A8048",
    accentRgb: "26,128,72",
    text: "#071510",
    subText: "#366048",
    cardBg: "#FFFFFF",
    borderColor: "#B6E0C8",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    tagline: "Train Without Limits",
    headline: "Gear That Moves\nWith You",
    sub: "Performance accessories for every discipline — from gym to trail to court.",
    stat1: { value: "Pro", label: "Grade" },
    stat2: { value: "Sweat", label: "Proof" },
    stat3: { value: "Athlete", label: "Tested" },
    pill: "Shop Sports",
    layout: "bold",
  },

  sunglasses: {
    bg: "#F7FAF8",
    bgGradient: "linear-gradient(160deg, #F7FAF8 0%, #EAF4EE 50%, #F7FAF8 100%)",
    accent: "#3A8060",
    accentRgb: "58,128,96",
    text: "#0A1A10",
    subText: "#4A7260",
    cardBg: "#FFFFFF",
    borderColor: "#C2E2D4",
    fontFamily: "'DM Serif Display', serif",
    tagline: "See the World in Style",
    headline: "Frames for\nEvery Face",
    sub: "UV400 protection meets runway-ready style. Sunglasses for every season.",
    stat1: { value: "UV400", label: "Protection" },
    stat2: { value: "TAC", label: "Polarised" },
    stat3: { value: "50+", label: "Frames" },
    pill: "Shop Shades",
    layout: "editorial",
  },

  tablets: {
    bg: "#F5FAF7",
    bgGradient: "linear-gradient(135deg, #F5FAF7 0%, #E4F2EC 50%, #F5FAF7 100%)",
    accent: "#1E7248",
    accentRgb: "30,114,72",
    text: "#081510",
    subText: "#386650",
    cardBg: "#FFFFFF",
    borderColor: "#BAE0CE",
    fontFamily: "'Inter', sans-serif",
    tagline: "Create. Learn. Play.",
    headline: "Tablets Built for\nWhat You Do",
    sub: "Whether you sketch, stream, study or present — there's a tablet made for it.",
    stat1: { value: "OLED", label: "Display" },
    stat2: { value: "S-Pen", label: "Support" },
    stat3: { value: "All", label: "Brands" },
    pill: "Shop Tablets",
    layout: "tech",
  },

  tops: {
    bg: "#F8FAF8",
    bgGradient: "linear-gradient(150deg, #F8FAF8 0%, #EDF5F0 50%, #F8FAF8 100%)",
    accent: "#2E7858",
    accentRgb: "46,120,88",
    text: "#0A1A10",
    subText: "#446A56",
    cardBg: "#FFFFFF",
    borderColor: "#C4E2D4",
    fontFamily: "'Cormorant Garamond', serif",
    tagline: "Effortlessly You",
    headline: "Tops That Do\nAll the Talking",
    sub: "Relaxed fits, bold prints, classic silhouettes. The wardrobe staples you'll reach for every day.",
    stat1: { value: "Soft", label: "Fabrics" },
    stat2: { value: "New", label: "Weekly" },
    stat3: { value: "XS–4XL", label: "Sizes" },
    pill: "Shop Tops",
    layout: "editorial",
  },

  vehicle: {
    bg: "#F5FAF6",
    bgGradient: "linear-gradient(135deg, #F5FAF6 0%, #E4F2E9 50%, #F5FAF6 100%)",
    accent: "#226040",
    accentRgb: "34,96,64",
    text: "#081510",
    subText: "#3A5E48",
    cardBg: "#FFFFFF",
    borderColor: "#BCDECE",
    fontFamily: "'DM Serif Display', serif",
    tagline: "Drive What You Love",
    headline: "Parts & Accessories\nFor Every Ride",
    sub: "OEM quality parts, performance upgrades and detailing essentials for every vehicle.",
    stat1: { value: "OEM", label: "Quality" },
    stat2: { value: "Fits", label: "All Makes" },
    stat3: { value: "Fast", label: "Dispatch" },
    pill: "Shop Vehicle",
    layout: "bold",
  },

  "womens-bags": {
    bg: "#F7FAF8",
    bgGradient: "linear-gradient(160deg, #F7FAF8 0%, #EAF4EE 50%, #F7FAF8 100%)",
    accent: "#337560",
    accentRgb: "51,117,96",
    text: "#0A1A12",
    subText: "#466A58",
    cardBg: "#FFFFFF",
    borderColor: "#C2E2D4",
    fontFamily: "'Cormorant Garamond', serif",
    tagline: "Carry Your World",
    headline: "Bags That Make\na Statement",
    sub: "From tote to clutch — luxuriously crafted bags for every occasion and every outfit.",
    stat1: { value: "Hand", label: "Stitched" },
    stat2: { value: "Vegan", label: "Leather" },
    stat3: { value: "Limited", label: "Editions" },
    pill: "Shop Bags",
    layout: "editorial",
  },

  "womens-dresses": {
    bg: "#F8FAF8",
    bgGradient: "linear-gradient(160deg, #F8FAF8 0%, #EDF5F0 50%, #F8FAF8 100%)",
    accent: "#2A7A56",
    accentRgb: "42,122,86",
    text: "#0A1A10",
    subText: "#426E56",
    cardBg: "#FFFFFF",
    borderColor: "#C0E2D2",
    fontFamily: "'Cormorant Garamond', serif",
    tagline: "Dress the Moment",
    headline: "From Casual to\nBlack Tie",
    sub: "Flowing silhouettes, bold patterns, timeless cuts. The dress for every occasion.",
    stat1: { value: "New", label: "Arrivals" },
    stat2: { value: "Eco", label: "Fabric" },
    stat3: { value: "XS–3XL", label: "Sizes" },
    pill: "Shop Dresses",
    layout: "editorial",
  },

  "womens-jewellery": {
    bg: "#F6FAF7",
    bgGradient: "linear-gradient(135deg, #F6FAF7 0%, #E7F3EC 50%, #F6FAF7 100%)",
    accent: "#1C6E48",
    accentRgb: "28,110,72",
    text: "#081510",
    subText: "#3A6450",
    cardBg: "#FFFFFF",
    borderColor: "#BEE0CE",
    fontFamily: "'Cormorant Garamond', serif",
    tagline: "Wear Your Story",
    headline: "Fine Jewellery\nFor Every Chapter",
    sub: "18k gold, sterling silver, precious stones. Pieces that mark the moments that matter.",
    stat1: { value: "18k", label: "Gold" },
    stat2: { value: "GIA", label: "Certified" },
    stat3: { value: "Life", label: "Polish" },
    pill: "Shop Jewellery",
    layout: "editorial",
  },

  "womens-shoes": {
    bg: "#F7FAF8",
    bgGradient: "linear-gradient(160deg, #F7FAF8 0%, #EBF4EF 50%, #F7FAF8 100%)",
    accent: "#307858",
    accentRgb: "48,120,88",
    text: "#0A1A10",
    subText: "#446C58",
    cardBg: "#FFFFFF",
    borderColor: "#C2E2D4",
    fontFamily: "'Cormorant Garamond', serif",
    tagline: "Step Into Yourself",
    headline: "Shoes for Every\nVersion of You",
    sub: "Heels, flats, boots and sneakers — designed for the woman who never stops moving.",
    stat1: { value: "True", label: "To Size" },
    stat2: { value: "Arch", label: "Support" },
    stat3: { value: "200+", label: "Styles" },
    pill: "Shop Shoes",
    layout: "editorial",
  },

  "womens-watches": {
    bg: "#F6FAF7",
    bgGradient: "linear-gradient(135deg, #F6FAF7 0%, #E8F4EC 50%, #F6FAF7 100%)",
    accent: "#267060",
    accentRgb: "38,112,96",
    text: "#081A10",
    subText: "#3C6458",
    cardBg: "#FFFFFF",
    borderColor: "#BEE0D2",
    fontFamily: "'Cormorant Garamond', serif",
    tagline: "Elegance on Your Wrist",
    headline: "Timepieces\nfor Her",
    sub: "Rose gold, mother of pearl, diamond-set bezels. Watches as refined as the woman wearing them.",
    stat1: { value: "Swiss", label: "Quartz" },
    stat2: { value: "Diamond", label: "Set" },
    stat3: { value: "Gift", label: "Ready" },
    pill: "Shop Watches",
    layout: "editorial",
  },
};

export function getTheme(category) {
  return CATEGORY_THEMES[category] || CATEGORY_THEMES.all;
}