// ─── Category Theme Config ────────────────────────────────────────────────────
// Each entry drives the hero section AND the product-card accent colours
// when that category is active.

export const CATEGORY_THEMES = {
  all: {
    bg: "#0A0A0F",
    bgGradient: "linear-gradient(135deg, #0A0A0F 0%, #1A1A2E 50%, #0A0A0F 100%)",
    accent: "#C9A96E",
    accentRgb: "201,169,110",
    text: "#F5F5F0",
    subText: "#8888A0",
    cardBg: "#1A1A24",
    borderColor: "#2A2A38",
    fontFamily: "'Playfair Display', serif",
    tagline: "Every Category. One Destination.",
    headline: "Discover Our\nFull Collection",
    sub: "From beauty to tech, groceries to furniture — curated products at your fingertips.",
    stat1: { value: "30+", label: "Products" },
    stat2: { value: "10+", label: "Categories" },
    stat3: { value: "4.5★", label: "Avg Rating" },
    pill: "All Products",
    layout: "centered",
  },

  beauty: {
    bg: "#FDF6EE",
    bgGradient: "linear-gradient(160deg, #FDF6EE 0%, #F5E6D3 40%, #EDD5B8 100%)",
    accent: "#B5704A",
    accentRgb: "181,112,74",
    text: "#1C1008",
    subText: "#7A5C44",
    cardBg: "#FFFFFF",
    borderColor: "#E8D5C0",
    fontFamily: "'Cormorant Garamond', serif",
    tagline: "Nurture Your Glow",
    headline: "Reveal Your\nNatural Beauty",
    sub: "Gentle formulas crafted to hydrate, restore, and elevate your skin every day.",
    stat1: { value: "60k", label: "Happy Clients" },
    stat2: { value: "100%", label: "Cruelty Free" },
    stat3: { value: "4.8★", label: "Rated" },
    pill: "Shop Beauty",
    layout: "editorial",
  },

  fragrances: {
    bg: "#0D0B18",
    bgGradient: "linear-gradient(135deg, #0D0B18 0%, #1A1530 50%, #12102A 100%)",
    accent: "#9B7FD4",
    accentRgb: "155,127,212",
    text: "#EDE8FF",
    subText: "#9985CC",
    cardBg: "#16132A",
    borderColor: "#2E2850",
    fontFamily: "'Cormorant Garamond', serif",
    tagline: "Scent is Memory",
    headline: "Find Your\nSignature Scent",
    sub: "Rare ingredients, masterful compositions. Fragrances that become unmistakably you.",
    stat1: { value: "200+", label: "Scents" },
    stat2: { value: "12", label: "Families" },
    stat3: { value: "Luxury", label: "Grade" },
    pill: "Explore Scents",
    layout: "dark-luxury",
  },

  furniture: {
    bg: "#F7F3EE",
    bgGradient: "linear-gradient(150deg, #F7F3EE 0%, #EDE5D8 60%, #E0D4C0 100%)",
    accent: "#6B5B45",
    accentRgb: "107,91,69",
    text: "#1A1410",
    subText: "#6B5B45",
    cardBg: "#FFFFFF",
    borderColor: "#D8CDB8",
    fontFamily: "'DM Serif Display', serif",
    tagline: "Craft for Living",
    headline: "Spaces That\nTell Your Story",
    sub: "Timeless pieces, honest materials. Furniture built to last generations.",
    stat1: { value: "50yr", label: "Durability" },
    stat2: { value: "FSC", label: "Certified" },
    stat3: { value: "Bespoke", label: "Made" },
    pill: "Browse Furniture",
    layout: "editorial",
  },

  groceries: {
    bg: "#0F1F0A",
    bgGradient: "linear-gradient(145deg, #0F1F0A 0%, #162B0E 50%, #0A1808 100%)",
    accent: "#5CB85C",
    accentRgb: "92,184,92",
    text: "#EEF5EC",
    subText: "#7AAD72",
    cardBg: "#162B0E",
    borderColor: "#2A4A22",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    tagline: "Fresh. Local. Yours.",
    headline: "Farm to Door\nEvery Morning",
    sub: "Seasonal produce, pantry staples, and specialty foods — delivered fresh.",
    stat1: { value: "Daily", label: "Harvest" },
    stat2: { value: "Zero", label: "Pesticides" },
    stat3: { value: "2hr", label: "Delivery" },
    pill: "Shop Fresh",
    layout: "bold",
  },

  "home-decoration": {
    bg: "#FAFAF7",
    bgGradient: "linear-gradient(150deg, #FAFAF7 0%, #F2EDE4 50%, #E8E0D4 100%)",
    accent: "#C4813A",
    accentRgb: "196,129,58",
    text: "#1A1610",
    subText: "#7A6A50",
    cardBg: "#FFFFFF",
    borderColor: "#DDD4C0",
    fontFamily: "'Libre Baskerville', serif",
    tagline: "Style Your Space",
    headline: "Every Corner\nDeserves Beauty",
    sub: "Curated décor to transform any room into a space that feels like you.",
    stat1: { value: "500+", label: "Styles" },
    stat2: { value: "Gift", label: "Ready" },
    stat3: { value: "Award", label: "Winning" },
    pill: "Decorate Now",
    layout: "editorial",
  },

  "kitchen-accessories": {
    bg: "#1A1208",
    bgGradient: "linear-gradient(140deg, #1A1208 0%, #2A1E0A 50%, #1A1208 100%)",
    accent: "#E8973A",
    accentRgb: "232,151,58",
    text: "#FFF8EE",
    subText: "#BBA070",
    cardBg: "#241A08",
    borderColor: "#3A2A10",
    fontFamily: "'Playfair Display', serif",
    tagline: "Cook with Confidence",
    headline: "Tools Built for\nReal Kitchens",
    sub: "Professional-grade accessories for home chefs who take their craft seriously.",
    stat1: { value: "Chef", label: "Approved" },
    stat2: { value: "Steel", label: "Grade" },
    stat3: { value: "10yr", label: "Warranty" },
    pill: "Equip Kitchen",
    layout: "dark-luxury",
  },

  laptops: {
    bg: "#070B14",
    bgGradient: "linear-gradient(135deg, #070B14 0%, #0D1526 50%, #070B14 100%)",
    accent: "#3B9EFF",
    accentRgb: "59,158,255",
    text: "#E8F0FF",
    subText: "#6B90C0",
    cardBg: "#0D1526",
    borderColor: "#1A2A44",
    fontFamily: "'Inter', sans-serif",
    tagline: "Power Your Work",
    headline: "Next-Gen Laptops\nFor Every Need",
    sub: "From ultra-thin to workstation-grade — performance laptops that keep up with you.",
    stat1: { value: "M4", label: "Chipsets" },
    stat2: { value: "4K", label: "Displays" },
    stat3: { value: "20hr", label: "Battery" },
    pill: "Shop Laptops",
    layout: "tech",
  },

  "mens-shirts": {
    bg: "#111418",
    bgGradient: "linear-gradient(150deg, #111418 0%, #1C2228 50%, #111418 100%)",
    accent: "#E8E0D0",
    accentRgb: "232,224,208",
    text: "#F0EDE8",
    subText: "#8888A0",
    cardBg: "#1C2228",
    borderColor: "#2A3040",
    fontFamily: "'DM Serif Display', serif",
    tagline: "Dressed with Intent",
    headline: "The Modern\nGentleman's Edit",
    sub: "Premium fabrics, precise cuts. Shirts crafted for those who dress with purpose.",
    stat1: { value: "Slim", label: "Fit" },
    stat2: { value: "100%", label: "Cotton" },
    stat3: { value: "Tailored", label: "Cut" },
    pill: "Shop Shirts",
    layout: "dark-luxury",
  },

  "mens-shoes": {
    bg: "#0E0C08",
    bgGradient: "linear-gradient(135deg, #0E0C08 0%, #1C1810 50%, #0E0C08 100%)",
    accent: "#D4A843",
    accentRgb: "212,168,67",
    text: "#F5F0E8",
    subText: "#9A8A60",
    cardBg: "#1C1810",
    borderColor: "#302A18",
    fontFamily: "'Cormorant Garamond', serif",
    tagline: "Walk with Authority",
    headline: "Shoes That Define\nYour Stride",
    sub: "Handcrafted leather, heritage silhouettes. Built for the man who means business.",
    stat1: { value: "Hand", label: "Crafted" },
    stat2: { value: "Full", label: "Grain Leather" },
    stat3: { value: "Classic", label: "Since 1998" },
    pill: "Shop Shoes",
    layout: "dark-luxury",
  },

  "mens-watches": {
    bg: "#080808",
    bgGradient: "linear-gradient(135deg, #080808 0%, #141414 50%, #080808 100%)",
    accent: "#D4AF37",
    accentRgb: "212,175,55",
    text: "#F0ECD8",
    subText: "#806A30",
    cardBg: "#141414",
    borderColor: "#282018",
    fontFamily: "'Cormorant Garamond', serif",
    tagline: "Time is Everything",
    headline: "Precision\nPersonified",
    sub: "Swiss movements, sapphire crystals, timeless cases. A watch for every wrist.",
    stat1: { value: "Swiss", label: "Movement" },
    stat2: { value: "50m", label: "Water Resist" },
    stat3: { value: "Life", label: "Warranty" },
    pill: "Shop Watches",
    layout: "dark-luxury",
  },

  "mobile-accessories": {
    bg: "#080E1A",
    bgGradient: "linear-gradient(135deg, #080E1A 0%, #0E1830 50%, #080E1A 100%)",
    accent: "#00D4FF",
    accentRgb: "0,212,255",
    text: "#E0F0FF",
    subText: "#4A80A0",
    cardBg: "#0E1830",
    borderColor: "#1A2A44",
    fontFamily: "'Inter', sans-serif",
    tagline: "Stay Connected",
    headline: "Accessories for\nEvery Device",
    sub: "Cases, cables, chargers and more. Everything your phone needs, nothing it doesn't.",
    stat1: { value: "MFi", label: "Certified" },
    stat2: { value: "Fast", label: "Charge" },
    stat3: { value: "Drop", label: "Tested" },
    pill: "Shop Accessories",
    layout: "tech",
  },

  motorcycle: {
    bg: "#100A04",
    bgGradient: "linear-gradient(140deg, #100A04 0%, #1E1008 50%, #100A04 100%)",
    accent: "#FF4500",
    accentRgb: "255,69,0",
    text: "#FFF0E8",
    subText: "#A06040",
    cardBg: "#1E1008",
    borderColor: "#3A1A08",
    fontFamily: "'DM Serif Display', serif",
    tagline: "Born to Ride",
    headline: "Gear Up for\nEvery Road",
    sub: "Helmets, gloves, jackets. Riding gear engineered for performance and protection.",
    stat1: { value: "DOT", label: "Certified" },
    stat2: { value: "CE", label: "Armour" },
    stat3: { value: "Race", label: "Grade" },
    pill: "Shop Moto",
    layout: "bold",
  },

  "skin-care": {
    bg: "#FBF7F4",
    bgGradient: "linear-gradient(160deg, #FBF7F4 0%, #F2E8E0 50%, #E8D8CC 100%)",
    accent: "#A0634A",
    accentRgb: "160,99,74",
    text: "#1A0E0A",
    subText: "#8A6050",
    cardBg: "#FFFFFF",
    borderColor: "#E0CCC0",
    fontFamily: "'Cormorant Garamond', serif",
    tagline: "Skin Speaks First",
    headline: "Science-Backed\nSkin Rituals",
    sub: "Dermatologist-tested formulas that work with your skin, not against it.",
    stat1: { value: "Derm", label: "Tested" },
    stat2: { value: "Vegan", label: "Formula" },
    stat3: { value: "4.9★", label: "Rated" },
    pill: "Shop Skincare",
    layout: "editorial",
  },

  smartphones: {
    bg: "#050810",
    bgGradient: "linear-gradient(135deg, #050810 0%, #0A1020 50%, #050810 100%)",
    accent: "#A78BFA",
    accentRgb: "167,139,250",
    text: "#F0EEFF",
    subText: "#7060A0",
    cardBg: "#0A1020",
    borderColor: "#1A1A38",
    fontFamily: "'Inter', sans-serif",
    tagline: "Pocket-Sized Power",
    headline: "The Smartphone\nYou Deserve",
    sub: "Latest flagships, mid-range gems, and budget picks. Find your perfect match.",
    stat1: { value: "5G", label: "Ready" },
    stat2: { value: "108MP", label: "Cameras" },
    stat3: { value: "All", label: "Brands" },
    pill: "Shop Phones",
    layout: "tech",
  },

  "sports-accessories": {
    bg: "#040E08",
    bgGradient: "linear-gradient(140deg, #040E08 0%, #081A10 50%, #040E08 100%)",
    accent: "#00E676",
    accentRgb: "0,230,118",
    text: "#E8FFF0",
    subText: "#408060",
    cardBg: "#081A10",
    borderColor: "#103020",
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    tagline: "Train Without Limits",
    headline: "Gear That Moves\nWith You",
    sub: "Performance accessories for every discipline — from gym to trail to court.",
    stat1: { value: "Pro", label: "Grade" },
    stat2: { value: "Sweat", label: "Proof" },
    stat3: { value: "Athlete", label: "Tested" },
    pill: "Shop Sports",
    layout: "bold",
  },

  sunglasses: {
    bg: "#FFF9F0",
    bgGradient: "linear-gradient(160deg, #FFF9F0 0%, #FFF0D8 50%, #FFE4B8 100%)",
    accent: "#E8750A",
    accentRgb: "232,117,10",
    text: "#1A0C00",
    subText: "#8A6030",
    cardBg: "#FFFFFF",
    borderColor: "#F0D8A8",
    fontFamily: "'DM Serif Display', serif",
    tagline: "See the World in Style",
    headline: "Frames for\nEvery Face",
    sub: "UV400 protection meets runway-ready style. Sunglasses for every season.",
    stat1: { value: "UV400", label: "Protection" },
    stat2: { value: "TAC", label: "Polarised" },
    stat3: { value: "50+", label: "Frames" },
    pill: "Shop Shades",
    layout: "editorial",
  },

  tablets: {
    bg: "#0A0A14",
    bgGradient: "linear-gradient(135deg, #0A0A14 0%, #14142A 50%, #0A0A14 100%)",
    accent: "#60A5FA",
    accentRgb: "96,165,250",
    text: "#E8EEFF",
    subText: "#6070A0",
    cardBg: "#14142A",
    borderColor: "#202040",
    fontFamily: "'Inter', sans-serif",
    tagline: "Create. Learn. Play.",
    headline: "Tablets Built for\nWhat You Do",
    sub: "Whether you sketch, stream, study or present — there's a tablet made for it.",
    stat1: { value: "OLED", label: "Display" },
    stat2: { value: "S-Pen", label: "Support" },
    stat3: { value: "All", label: "Brands" },
    pill: "Shop Tablets",
    layout: "tech",
  },

  tops: {
    bg: "#FDF8F5",
    bgGradient: "linear-gradient(150deg, #FDF8F5 0%, #F5EDE8 50%, #EDE0D8 100%)",
    accent: "#C05A6A",
    accentRgb: "192,90,106",
    text: "#1A0808",
    subText: "#9A6060",
    cardBg: "#FFFFFF",
    borderColor: "#E8D0D0",
    fontFamily: "'Cormorant Garamond', serif",
    tagline: "Effortlessly You",
    headline: "Tops That Do\nAll the Talking",
    sub: "Relaxed fits, bold prints, classic silhouettes. The wardrobe staples you'll reach for every day.",
    stat1: { value: "Soft", label: "Fabrics" },
    stat2: { value: "New", label: "Weekly" },
    stat3: { value: "XS–4XL", label: "Sizes" },
    pill: "Shop Tops",
    layout: "editorial",
  },

  vehicle: {
    bg: "#080C10",
    bgGradient: "linear-gradient(135deg, #080C10 0%, #10181E 50%, #080C10 100%)",
    accent: "#FF6B35",
    accentRgb: "255,107,53",
    text: "#F0F4F8",
    subText: "#708090",
    cardBg: "#10181E",
    borderColor: "#1E2A34",
    fontFamily: "'DM Serif Display', serif",
    tagline: "Drive What You Love",
    headline: "Parts & Accessories\nFor Every Ride",
    sub: "OEM quality parts, performance upgrades and detailing essentials for every vehicle.",
    stat1: { value: "OEM", label: "Quality" },
    stat2: { value: "Fits", label: "All Makes" },
    stat3: { value: "Fast", label: "Dispatch" },
    pill: "Shop Vehicle",
    layout: "bold",
  },

  "womens-bags": {
    bg: "#FCF5F0",
    bgGradient: "linear-gradient(160deg, #FCF5F0 0%, #F5E8E0 50%, #EDD8CC 100%)",
    accent: "#8B4060",
    accentRgb: "139,64,96",
    text: "#1A0810",
    subText: "#8A5060",
    cardBg: "#FFFFFF",
    borderColor: "#E0C8CC",
    fontFamily: "'Cormorant Garamond', serif",
    tagline: "Carry Your World",
    headline: "Bags That Make\na Statement",
    sub: "From tote to clutch — luxuriously crafted bags for every occasion and every outfit.",
    stat1: { value: "Hand", label: "Stitched" },
    stat2: { value: "Vegan", label: "Leather" },
    stat3: { value: "Limited", label: "Editions" },
    pill: "Shop Bags",
    layout: "editorial",
  },

  "womens-dresses": {
    bg: "#FEF6FB",
    bgGradient: "linear-gradient(160deg, #FEF6FB 0%, #F8E8F4 50%, #F0D4EC 100%)",
    accent: "#A0407A",
    accentRgb: "160,64,122",
    text: "#1A041A",
    subText: "#906080",
    cardBg: "#FFFFFF",
    borderColor: "#E8C8E0",
    fontFamily: "'Cormorant Garamond', serif",
    tagline: "Dress the Moment",
    headline: "From Casual to\nBlack Tie",
    sub: "Flowing silhouettes, bold patterns, timeless cuts. The dress for every occasion.",
    stat1: { value: "New", label: "Arrivals" },
    stat2: { value: "Eco", label: "Fabric" },
    stat3: { value: "XS–3XL", label: "Sizes" },
    pill: "Shop Dresses",
    layout: "editorial",
  },

  "womens-jewellery": {
    bg: "#0A0808",
    bgGradient: "linear-gradient(135deg, #0A0808 0%, #1A1010 50%, #0A0808 100%)",
    accent: "#E8C878",
    accentRgb: "232,200,120",
    text: "#FFF8E8",
    subText: "#9A8050",
    cardBg: "#1A1010",
    borderColor: "#2A1E18",
    fontFamily: "'Cormorant Garamond', serif",
    tagline: "Wear Your Story",
    headline: "Fine Jewellery\nFor Every Chapter",
    sub: "18k gold, sterling silver, precious stones. Pieces that mark the moments that matter.",
    stat1: { value: "18k", label: "Gold" },
    stat2: { value: "GIA", label: "Certified" },
    stat3: { value: "Life", label: "Polish" },
    pill: "Shop Jewellery",
    layout: "dark-luxury",
  },

  "womens-shoes": {
    bg: "#FDF8FC",
    bgGradient: "linear-gradient(160deg, #FDF8FC 0%, #F5ECFA 50%, #EDD8F4 100%)",
    accent: "#7040A0",
    accentRgb: "112,64,160",
    text: "#100818",
    subText: "#806090",
    cardBg: "#FFFFFF",
    borderColor: "#DCC8E8",
    fontFamily: "'Cormorant Garamond', serif",
    tagline: "Step Into Yourself",
    headline: "Shoes for Every\nVersion of You",
    sub: "Heels, flats, boots and sneakers — designed for the woman who never stops moving.",
    stat1: { value: "True", label: "To Size" },
    stat2: { value: "Arch", label: "Support" },
    stat3: { value: "200+", label: "Styles" },
    pill: "Shop Shoes",
    layout: "editorial",
  },

  "womens-watches": {
    bg: "#0C0A14",
    bgGradient: "linear-gradient(135deg, #0C0A14 0%, #18142A 50%, #0C0A14 100%)",
    accent: "#E8A0C8",
    accentRgb: "232,160,200",
    text: "#F8EEF8",
    subText: "#8060A0",
    cardBg: "#18142A",
    borderColor: "#281E44",
    fontFamily: "'Cormorant Garamond', serif",
    tagline: "Elegance on Your Wrist",
    headline: "Timepieces\nfor Her",
    sub: "Rose gold, mother of pearl, diamond-set bezels. Watches as refined as the woman wearing them.",
    stat1: { value: "Swiss", label: "Quartz" },
    stat2: { value: "Diamond", label: "Set" },
    stat3: { value: "Gift", label: "Ready" },
    pill: "Shop Watches",
    layout: "dark-luxury",
  },
};

// Returns the theme for a category, falling back to "all"
export function getTheme(category) {
  return CATEGORY_THEMES[category] || CATEGORY_THEMES.all;
}